# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alan Cham
email: me@alanch.am
description: My blog and sandbox.
baseurl: /
url: https://blog.alanch.am

# Display
show_excerpts: true

# Organization
epics:
  - display: Linear Algebra
    tag: linear-algebra
  - display: UNIX
    tag: unix
  - display: Domain-Driven Design
    tag: domain-driven-design
  - display: Other
    tag: other

# Social
twitter_username: acham1
github_username: acham1
rss: feed.xml

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - README.md
